name: connecthub_app
description: ConnectHub mobile client.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  go_router: ^13.2.0
  dio: ^5.4.1
  flutter_secure_storage: ^9.0.0
  cached_network_image: ^3.3.1
  intl: ^0.19.0
  google_fonts: ^6.1.0
  ionicons: ^0.2.2
  gap: ^3.0.0
  flutter_dotenv: ^5.1.0
  flutter_animate: ^4.5.0
  image_picker: ^1.1.2
  web_socket_channel: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  riverpod_generator: ^2.4.0
  riverpod_annotation: ^2.3.5

flutter:
  uses-material-design: true
  assets:
    - .env
